import { writeFileSync } from "fs";
import { CLOUD_THEMES, DEFAULT_THEME } from "../lib/cloudTheme";

const FILE_TYPE_GRADIENTS = [
  "from-red-400", "to-red-500",
  "from-blue-400", "to-blue-500",
  "from-purple-400", "to-purple-500",
  "from-zinc-400", "to-zinc-500",
];

const GRADIENT_DIRECTIONS = [
  "bg-gradient-to-br",
  "bg-gradient-to-r",
  "bg-gradient-to-b",
];

function extractClasses(): string[] {
  const classes = new Set<string>();
  
  GRADIENT_DIRECTIONS.forEach(cls => classes.add(cls));
  
  Object.values(CLOUD_THEMES).forEach((theme) => {
    theme.heroBg.split(" ").forEach((c) => classes.add(c));
    theme.recentFilesBg.split(" ").forEach((c) => classes.add(c));
    theme.promptBarBg.split(" ").forEach((c) => classes.add(c));
  });
  
  DEFAULT_THEME.heroBg.split(" ").forEach((c) => classes.add(c));
  DEFAULT_THEME.recentFilesBg.split(" ").forEach((c) => classes.add(c));
  DEFAULT_THEME.promptBarBg.split(" ").forEach((c) => classes.add(c));
  
  FILE_TYPE_GRADIENTS.forEach(cls => classes.add(cls));
  
  return Array.from(classes).sort();
}

function generate() {
  const classes = extractClasses();
  const timestamp = new Date().toISOString();
  
  const content = `/**
 * AUTOGENERATED FILE - DO NOT EDIT
 * Generated by: scripts/generateTailwindSafelist.ts
 * Last updated: ${timestamp}
 * 
 * This file contains all Tailwind classes extracted from CLOUD_THEMES.
 * Run "npm run prepare:safelist" to regenerate.
 */

export const TAILWIND_SAFELIST: string[] = ${JSON.stringify(classes, null, 2)};
`;
  
  writeFileSync("generated/tailwindSafelist.ts", content);
  console.log(`Generated safelist with ${classes.length} classes`);
}

generate();
